### PR TITLE
add an annotation about client/HTTPS supports for docs of HTTPChaos

### PR DESCRIPTION
**Pull request by Hexilee**
Signed-off-by: hexilee <i@hexilee.me>

### CODE REVIEW

**Comment by Hexilee** [comment]
In en: [https://github.com/chaos-mesh/website/pull/127](https://github.com/chaos-mesh/website/pull/127)

**Comment by en-jin19** [comment]
@Hexilee could you please invite a technical reviewer to this PR? thanks!

**Comment by Hexilee** [comment]
In en: [https://github.com/chaos-mesh/website/pull/127](https://github.com/chaos-mesh/website/pull/127).

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Pull request merged**
